/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package authentication;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    DB db = new DB();
    
    
    public Login() {
        initComponents();
        getRootPane().setDefaultButton(login);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pass = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        register = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 990));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pass.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 0, 0));
        pass.setText("Password");
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, 130, 30));

        username1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        username1.setText("User LogIn");
        getContentPane().add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 260, 60));

        user.setBackground(new java.awt.Color(153, 0, 0));
        user.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(0, 0, 0));
        user.setText("User Name");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 130, 30));

        username.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 210, -1));

        login.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 750, -1, -1));

        register.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 830, -1, -1));

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authentication/New Project (4).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(650, 900));
        jLabel1.setMinimumSize(new java.awt.Dimension(650, 900));
        jLabel1.setPreferredSize(new java.awt.Dimension(650, 900));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 650, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       //  String sql = "SELECT * FROM `login`"; // Provide a valid SQL query to retrieve data
         String sql = "SELECT * FROM login WHERE Email = ? AND Password = ?";
         
         String hashpw = hashPassword(jPassword.getText());
         String email = username.getText();
         
         if(!email.isEmpty()&&!hashpw.isEmpty()){
         //  String hashpw = hashPassword(ps1);
        try {
        Connection cn = db.getCon();
        PreparedStatement pstmt = cn.prepareStatement(sql);
        pstmt.setString(1,email); // Assuming username.getText() retrieves the entered username
        pstmt.setString(2, hashpw); // Assuming jPassword.getText() retrieves the entered password^
        ResultSet rs = pstmt.executeQuery();
        
        if (rs.next()) {
            // If a row is found, the username and password are correct
            JOptionPane.showMessageDialog(null, "Login Successful!");
            int userId = rs.getInt("ID");
            
            this.dispose();
            Home h1 = new Home(userId);
            h1.setVisible(true);
            h1.setSize(650, 900);
        } else {
            // If no row is found, the username or password is incorrect
            System.out.println("Invalid Username or Password");
            JOptionPane.showMessageDialog(null, "Invalid Username or Password");
        }

        // Close the ResultSet, PreparedStatement, and Connection
        rs.close();
        pstmt.close();
        cn.close();
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }else{
             JOptionPane.showMessageDialog(null, "Please enter email and password");
         }
        
    }//GEN-LAST:event_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Register R1 = new Register();
        R1.setVisible(true);
        R1.setSize(650, 900);
        R1.setResizable(false);
      
    }//GEN-LAST:event_registerActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    public String hashPassword(String password) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(password.getBytes());
            StringBuilder hexString = new StringBuilder();

            for (byte b : hash) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }

            return hexString.toString();
        } catch (NoSuchAlgorithmException ex) {
            // Handle exception appropriately
            System.err.println("Error hashing password: " + ex.getMessage());
            return null;
        }
   }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Login().setVisible(true);
                Login log1 = new Login();
                log1.setVisible(true);
                log1.setSize(650, 900);
                log1.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton login;
    private javax.swing.JLabel pass;
    private javax.swing.JButton register;
    private javax.swing.JLabel user;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username1;
    // End of variables declaration//GEN-END:variables
}
